### ISSUE TITLE
cannot create directory '/bitnami/mariadb/data': Permission denied

### ISSUE THREAD

**Issue by deenu7724** [bitnami/bitnami-docker-drupal#113]
pods logs are 

```
Welcome to the Bitnami mariadb container
mariadb 10:58:06.20 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb 10:58:06.20 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb 10:58:06.21 Send us your feedback at containers@bitnami.com
mariadb 10:58:06.21
mariadb 10:58:06.21 INFO  ==> ** Starting MariaDB setup **
mariadb 10:58:06.30 INFO  ==> Validating settings in MYSQL_*/MARIADB_* env vars
mariadb 10:58:06.31 INFO  ==> Initializing mariadb database
**mkdir: cannot create directory '/bitnami/mariadb/data': Permission denied**
```
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):** IBM Kuberentes

**Comment by carrodher** [comment]
If you are using the Bitnami Drupal Helm chart, installed with the default options, this chart uses MariaDB as subchart with the data persisted in a volume.

The [Bitnami MariaDB image](https://github.com/bitnami/bitnami-docker-mariadb) stores the MariaDB data and configurations at the `/bitnami/mariadb` path of the container.
The chart mounts a [Persistent Volume](https://github.com/bitnami/charts/blob/master/bitnami/mariadb/kubernetes.io/docs/user-guide/persistent-volumes) volume at this location. The volume is created using dynamic volume provisioning, by default. An existing PersistentVolumeClaim can be defined.

As the MariaDB image [runs as non-root](https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html) by default, it is necessary to adjust the ownership of the persistent volume so that the container can write data into it.
By default, the chart is configured to use [Kubernetes Security Context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) to automatically change the ownership of the volume. However, this feature does not work in all Kubernetes distributions. As an alternative, this chart supports using an initContainer to change the ownership of the volume before mounting it in the final destination.
You can enable this initContainer by setting `mariadb.volumePermissions.enabled` to `true` when installing the chart:
```
helm install ... --set mariadb.volumePermissions.enabled=true
```
or
```yaml
mariadb:
  volumePermissions:
    enabled: true
```

Not sure if this is your use case and the issue you are facing. If my answer is not properly oriented, please, can you fill the template that appears when creating a new issue? It is very useful for us in order to provide good support here.
