### ISSUE TITLE
How to upgrade Drupal

### ISSUE THREAD

**Issue by howtogithub-user** [bitnami/bitnami-docker-drupal#115]
Hello,
I am trying to find the correct way to install and maintain drupal into a production kubernetes cluster. I am disappointed to say that I cannot find documentation covering installation, upgrade and extension of Drupal using the Drupal recommended way, which is composer.

I used the bitnami drupal helm chart to install Drupal to a kubernetes cluster.
Instead of using directly the bitnami docker image in the helm values.yml we load our custom image which we have created using the bitnami image:

- The custom dockerfile uses the bitnami image: bitnami/drupal:9.0.2-debian-10-r3 

- it also performs some other steps like installing vim, git 

- and copying our custom modules and our composer.json(which has all the contributed modules we want to install) into the container root folder.
- Copies our custom bash script that will be executed after drupal is setup. Our custom bash script will run composer install to install contributed modules and will import configuration using drush config:import.

All OK until this step, the environment is up having our custom and contributed modules/themes/configuration enabled.

How can we update Drupal to the latest version? I tried the following:

- update the dockerfile to use newest version of bitnami image, let's say 9.0.5-debian-10-r8 release
- copy my updated composer.json into opt/bitnami/drupal
- run composer install, in order to update the db??

 but it throws an error :   Could not delete /opt/bitnami/drupal/sites/default/default.settings.php:

Are we following a wrong approach? Shouldn't we extend drupal updating the composer.json but using drush instead?

Thank you

**Comment by dani8art** [comment]
Hi @howtogithub-user thanks for opening the issue,

I think the approach to update your own image to the latest bitnami one should be updating the tag in the `FROM` statement, that's correct.

Regarding the updated `composer.json`, I think you should follow the same process that for the first time (drush) after that you should run composer install.

**Comment by stoopman** [comment]
Hi @howtogithub-user Did you ever get this to work properly? I'm in the same situation as you. I have an existing project, setup the recommended Drupal way through composer. And I have a hard time figuring out how to integrate all our custom, modules, contrib modules and external libraries from /vendor into this image. Also the regular drupal document root is /web, which is also not present in the Bitnami image. Could you share some of your experience? Maybe with some examples? Much appreciated!

**Comment by randradas** [comment]
Hello @stoopman it looks like the ticket is closed and the user who created the original issue is far from here. I'm not pretty sure whether @howtogithub-user fixed it or not but, have you tried the approach suggested by @dani8art?

**Comment by haithamshahin333** [comment]
+1 to @stoopman, I'm running into the same issue given that the recommended project uses /web and composer.json and vendor are referencing this directory, so copying the composer.json and associated vendor folder into the container creates issues since it is assuming the site is under /web. Any example the team can provide?

**Comment by marcosbc** [comment]
@haithamshahin333 Note that we have designed the Drupal container to persist files that are not meant to be changed with an upgrade, so that you can upgrade Drupal by simply changing the Docker image tag. Not sure why you mention composer.json and vendor folders, since you shouldn't need to worry about that.

**Comment by haithamshahin333** [comment]
Thanks @marcosbc - what I'm trying to think through is the DevOps workflow to continually update your Drupal instance through automation. For example, if we assume that modules/configuration etc. would all be managed through a dev workflow, and we also assume that the repo is following the recommended-project structure when you run a `composer create-project`, then a `composer install` would be run as part of your pipeline, which installs associated dependencies in modules, themes, etc. These then would not need to be persisted, and you would need to add a custom script to this image to copy over those directories into the image and run associated drush commands to import the required configuration.

Running `composer install` also installs libraries into the Vendor folder and generates the autoload.php file which is build off the recommended-project repo structure. Therefore, if we then try to do the same thing for the /vendor folder where we copy over the vendor directory that was produced as part of the pipeline after the `composer install` runs, the autoload.php that was copied over does not align with what is currently in the image and associated index.php file since the directory structure of the container does not have a web/ root for the site.

What I'm trying to get perspectives on is 1) if the pipeline workflow I'm describing above makes sense and 2) if it is expected that the /vendor directory would need to be copied over, or if we should assume that even with the workflow described above, the vendor directory in the built image shouldn't need to be updated. Wondering if the team has thoughts on how to continually update the container as part of a good DevOps workflow versus just the initial install.

**Comment by rafariossaa** [comment]
Hi, 
  Not sure if I can give a good advise on this as we don't develop on drupal. I thinks this going to depend on you workflow and which aspects are important for you. Each approach has it cons and pros, maybe you can try both and evaluate the approach based on your current workflow. Sometimes even small changes in the workflow are advisable if you can get a better integration of all the process.
