### ISSUE TITLE
Support for running cron

### ISSUE THREAD

**Issue by mikaelkundert** [bitnami/bitnami-docker-drupal#121]
Currently Drupal does not run CRON automatically and requires user admin to login and click it manually. Best practice is to run `drush cron` every minute.

The pod already has `drush` available, so you should be able to make a scheduled K8S CronJob using same base image.

**Comment by rafariossaa** [comment]
Hi @mikaelkundert ,
  Thanks for suggesting this. I am creating an internal task to analyze and implement this feature, however I can not provide a ETA for it. We will come back as soon as we have news, meanwhile feel free to send a PR implementing this or other features/fixes, we will be glad to review and merge it.

**Comment by dejan9393** [comment]
Would love to see this supported. I've been looking at trying to create a PR for this, but running the `entrypoint.sh` script without a webserver (i.e. running entrypoint without passing in `/opt/bitnami/scripts/apache/run.sh`) is proving non-trivial

**Comment by randradas** [comment]
Hello @dejan9393 thank you for your comment. Regarding your problem have you tried using the docker-compose file included in the repo? executing something like this should help you to run drupal:

```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-drupal/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```

Other than that once it is running you should be able to test changes just modifying the whatever is needed to incorporate the cron task.

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-drupal#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
