### ISSUE TITLE
Use MPM Event with php-fpm

### ISSUE THREAD

**Issue by benoitcdmnt** [bitnami/bitnami-docker-drupal#135]
I'm very surprised to see that php is still loaded through mpm prefork, and libphp without php fpm running in the container.
It's a very bad practice and can impact performance. 

Your other stack with drupal + nginx do it well, is there any plan to switch to this "way" ?

Thank you

**Comment by marcosbc** [comment]
Hi @benoitcdmnt, thanks for the feedback. The main reason is that enabling PHP-FPM like in the Drupal+NGINX image forces us to follow non-standard practices, by running multiple services in the same container at once (PHP-FPM + the web server). You can find an example [here](https://github.com/bitnami/bitnami-docker-php-fpm/blob/master/example/docker-compose.yml).

Ideally with PHP-FPM, the recommended approach would be to run them in different containers, however that requires access to the Drupal filesystem for both NGINX (static files) and PHP-FPM (application code) in order for the page to fully function. But with the current implementation, due to only persisting certain folders of the Drupal app (and not the entire web app), it means we would require two container images for doing this correctly: One for NGINX and one for PHP-FPM, both containers with the app contents installed.

Due to all this, for now we have postponed the implementation of PHP-FPM support for Drupal and other PHP app containers since each approach has its pros and cons.

However, we do have an internal task where we are discussing this. I'm going to link this issue to the task so we add any update. Unfortunately I'm unable to provide any ETA at this point.

**Comment by benoitcdmnt** [comment]
Okay, thank you for the clarification
