### ISSUE TITLE
Drupal 9.3.13 is already out on May 11th, Is there any upgrade problem?

### ISSUE THREAD

**Issue by ddfiberglass** [bitnami/bitnami-docker-drupal#144]
### Name and Version

bitnami/bitnami-docker-drupal

### What is the problem this feature will solve?

Is there any problem for the version Drupal 9.3.12 upgrade to 9.3.13, the bot has not upgraded yet? 

### What is the feature you are proposing to solve the problem?

Please help check this.

**Comment by carrodher** [comment]
Thanks for letting us know. This version introduces some changes that are not passing our tests, that's why it is not being automatically released. We need to manually work on adapting the automated test & release pipeline to the new version.

We will update this GH ticket once released the new version.

**Comment by ddfiberglass** [comment]
Thanks.
