### ISSUE TITLE
Nginx support

### ISSUE THREAD

**Issue by mhavelant** [bitnami/bitnami-docker-drupal#60]
Hi!

Is there a way to use nginx instead of apache?

**Comment by prydonius** [comment]
Hey @mhavelant, currently this image doesn't support Nginx.

Is there any particular reason you'd like to see Nginx support? Another option could be to add support for php-fpm in this image and proxy from either Apache or Nginx.

**Comment by mhavelant** [comment]
No particular reason, I'm just curious about this image and the possibilities. 
That php-fpm solution would be nice to give people options, and would be more in-line with the docker best practices as well! :)

**Comment by prydonius** [comment]
@mhavelant agreed. Thanks for bringing it up, we'll definitely keep this in mind!

**Comment by chepurko** [comment]
Hi, @prydonius how about simply because of pure speed and memory usage benefits? With NGINX/FPM and `fastcgi_cache` setup I can hit a single server hundreds of times per second indefinitely without missing a beat while the corresponding Apache/non-FPM version would crumble and grind to a halt...

I would love to tackle this as I'm keen on implementing this in a [Kubernetes cluster](https://github.com/chepurko/k8s-lemp), but first I suppose I would need to familiarise myself with `nami` packages and implement NGINX and PHP-FPM with `bitnami-pkg` in the Dockerfile...

**Comment by stoopman** [comment]
Hi, I would also love to see support for a Nginx setup!

I'm curious why you decided to put both Apache and php-fpm in a single image. I know the 'one process per container' is a recommended rule of thumb, but is regarded more as a guideline, not a hard rule. On the other hand I really like the approach of IBM's Drupal 8 K8 stack https://github.com/IBM/drupal-nginx-php-kubernetes. 

What are you thoughts on this?

**Comment by jotamartos** [comment]
Hi @stoopman,

Right now we are using 'Apache + mod_php' in one container making it simple for users. This way we have one process per container.

In any case, the IBM's approach is focused on k8s and for production environments and we are working on moving our containers to support those scenarios. We will have the IBM's approach in mind to improve the quality of our solution in the future.

Thank you for taking the time to share it.

**Comment by stoopman** [comment]
Hi @jotamartos,

Thanks for you reply. As you said IBM's approach is more focussed on production level, does that mean the Bitnami Drupal image is more focused on development and not ready for production yet?

Looking at the helm chart https://github.com/kubernetes/charts/tree/master/stable/drupal, which also uses this image, I'd assume this is ready to use in production..

**Comment by jotamartos** [comment]
Hi @stoopman,

As I mentioned, we are working on modifying our solutions to support that scenario. Right now, our solution uses "Apache + mod_php", one single process that you can configure inside the container. Our configuration of the application and all its required components has performance and security in mind. For example, the IBM's solution includes an [old version of Drupal](https://github.com/IBM/drupal-nginx-php-kubernetes/blob/master/code/drupal-version.txt), released in [last August](https://www.drupal.org/project/drupal/releases/8.3.7) while the Bitnami's one includes the latest version with the latest security fixes. Before publishing, we test all our solutions so the users won't find issues when deploying them.

That said, in case you want to use NGINX and PHP-FPM, you will need to use the IBM's solution or any other one that supports that topology for now. Otherwise, you can use the Bitnami's one and we will be more than happy to hear all your suggestions about this solution.

Thanks.

**Comment by carrodher** [comment]
Taking advantage of the stale bot message, before close the issue I want to share the Bitnami Drupal with Nginx container: https://github.com/bitnami/bitnami-docker-drupal-nginx
